### ISSUE TITLE
Manba button

### ISSUE THREAD

**Issue by Xayrulloh** [Xayrulloh/ReminderBot#109]

**Comment by Xayrulloh** [comment]
https://www.ziyouz.com/books/islomiy/hadis/Imom%20Navaviy.%20Riyozus%20solihiyn.pdf

link

**Comment by eugene0928** [comment]
qaysi qismgacha qilgansiz

**Comment by Xayrulloh** [comment]
qismni o'zi yo'q

**Comment by Xayrulloh** [comment]
button qo'wiw kere Manba dgan bosa ili pdf beriwimis kere ili link manimca pdf yaxwi, faqat uni tepadigi linkdan buffer holatda ob turib uyoga file ko'riniwda jo'natiw kere, ya'ni serverda saqlamen.
