### ISSUE TITLE
add hadith to inline_query and link to bot

### ISSUE THREAD

**Issue by Xayrulloh** [Xayrulloh/ReminderBot#110]

**Comment by atoshmukhamedov** [comment]
I need more detailed information

**Comment by Xayrulloh** [comment]
![Image](https://github.com/Xayrulloh/ReminderBot/assets/91729108/b2810c3d-ce96-4917-8503-92acc9699e81)


wuni tegida hadis

**Comment by atoshmukhamedov** [comment]
Is is a bog?

**Comment by Xayrulloh** [comment]
oldin qimoqci bo'b esimdan cqb qob ketganicun wunaqa db qo'ydim
