### ISSUE TITLE
need to format the message of hadis, stop inline query loading, deleting last message

### ISSUE THREAD

**Issue by Xayrulloh** [Xayrulloh/ReminderBot#111]

**Comment by Xayrulloh** [comment]
or need to change format

![Image](https://github.com/Xayrulloh/ReminderBot/assets/91729108/af78dac3-c9a4-4ed2-ab02-71a582dec159)

**Comment by atoshmukhamedov** [comment]
Should I fix it from database?

**Comment by Xayrulloh** [comment]
No,  I think we need to change format when sending

**Comment by Xayrulloh** [comment]
![Image](https://github.com/Xayrulloh/ReminderBot/assets/91729108/a8d28b4a-db97-4392-9544-e64808f940a3)
